"""Serial command layer for the Muto expansion board.

Deliberately has no dependency on the vendor libraries. ``MutoLib`` is not what
this robot loads, and ``muto_hexapod_lib`` -- which is -- lives outside every
path the ROS container mounts. Rather than depend on a library that may or may
not be importable, this module builds the board's frames directly. The frame
format was read from ``MutoLibCore.__send`` and the generated bytes compared
against it.

Only the firmware-gait commands are implemented. The software gait (``move()``)
computes inverse kinematics on the Pi and blocks for a full ~0.65 s cycle per
call; the firmware gaits are a single frame that the board runs by itself, which
is what lets the camera keep moving smoothly while the robot walks.

Every command is write-only. The board acknowledges nothing, out-of-range values
are clamped rather than rejected, and there is no position feedback anywhere.
"""

import threading
import time

import serial
from serial.tools import list_ports

# The expansion board is a CH340. The lidar on the same host is a CP2102, so
# vendor/product is enough to tell them apart.
BOARD_VID = 0x1A86
BOARD_PID = 0x7523

# Resolve the device instead of hard-coding a path. /dev/myserial is a udev
# symlink that exists on the host and NOT inside the ROS container, which gets
# its own /dev, and raw ttyUSB numbering is not stable across replugging.
AUTO_PORT = 'auto'

# Frame: HEAD DEVICE_ID LEN WRITE_CMD ADDR <payload> CHECKSUM 0x00 0xAA
HEAD = 0x55
DEVICE_ID = 0x00
WRITE_CMD = 0x01
TAIL = (0x00, 0xAA)

# Command addresses, read from MutoLibCore's ORDER table.
ADDR_RESET = 0x06
ADDR_SQUATS = 0x10
ADDR_STAY_PUT = 0x11
ADDR_FORWARD = 0x12
ADDR_BACKWARD = 0x13
ADDR_SHIFT_LEFT = 0x14
ADDR_SHIFT_RIGHT = 0x15
ADDR_TURN_LEFT = 0x16
ADDR_TURN_RIGHT = 0x17
ADDR_BUZZER = 0x18
ADDR_HEIGHT = 0x19
ADDR_RUN_TIME = 0x23
ADDR_PWM_SERVO = 0x25
ADDR_TORQUE_ON = 0x26
ADDR_TORQUE_OFF = 0x27

# Vendor limits. The board clamps silently, so these are enforced here instead:
# a clamped value is indistinguishable from an accepted one on the wire.
STEP_MIN, STEP_MAX = 10, 25
SPEED_MIN, SPEED_MAX = 1, 5
HEIGHT_MIN, HEIGHT_MAX = 1, 3
PAN_MIN, PAN_MAX = 0, 180
TILT_MIN, TILT_MAX = 0, 115

# -1 tells the board to leave that gimbal axis untouched.
GIMBAL_HOLD = -1

# MutoLibCore sleeps 1 ms after every write. The board drops frames without it.
WRITE_DELAY = 0.001

# Direction names as the gait methods use them.
GAITS = ('forward', 'backward', 'left', 'right', 'turn_left', 'turn_right')

_GAIT_ADDR = {
    'forward': ADDR_FORWARD,
    'backward': ADDR_BACKWARD,
    'left': ADDR_SHIFT_LEFT,
    'right': ADDR_SHIFT_RIGHT,
    'turn_left': ADDR_TURN_LEFT,
    'turn_right': ADDR_TURN_RIGHT,
}


def clamp(value, low, high):
    return max(low, min(high, value))


def find_board_port():
    """Return the CH340's device path, or raise with what was actually found.

    Guessing wrong here means writing gait frames at the lidar, so an ambiguous
    result is an error rather than a best guess.
    """
    matches = [p.device for p in list_ports.comports()
               if p.vid == BOARD_VID and p.pid == BOARD_PID]
    if len(matches) == 1:
        return matches[0]
    seen = ', '.join(
        f'{p.device} ({p.vid:04x}:{p.pid:04x})' if p.vid else f'{p.device} (no USB id)'
        for p in list_ports.comports()) or 'nothing'
    if not matches:
        raise RuntimeError(
            f'no CH340 ({BOARD_VID:04x}:{BOARD_PID:04x}) found. Serial ports present: {seen}')
    raise RuntimeError(f'{len(matches)} CH340 devices found ({", ".join(matches)}); '
                       'set the port parameter explicitly')


def build_frame(addr, payload):
    """Build one write frame, matching MutoLibCore.__send."""
    length = len(payload) + 0x08
    checksum = 255 - ((length + WRITE_CMD + addr + sum(payload)) % 256)
    return bytes([HEAD, DEVICE_ID, length, WRITE_CMD, addr,
                  *payload, checksum, *TAIL])


class MutoBoard:
    """Owns the serial port. One instance per process, one process per port.

    The port is exclusive in practice but not enforced by the kernel: pyserial
    opens a device another process already holds, and the two writers interleave
    bytes into corrupt frames. Nothing detects this at runtime, so check who
    holds the port before constructing this.

    All public methods are safe to call from any thread -- writes are serialised
    behind a lock, because a frame split across two threads is a frame the board
    silently discards.
    """

    def __init__(self, port=AUTO_PORT, baud=115200):
        if port == AUTO_PORT:
            port = find_board_port()
        self._lock = threading.Lock()
        self._serial = serial.Serial(port, baud, timeout=0.05)
        self.port = port

    def close(self):
        with self._lock:
            if self._serial.is_open:
                self._serial.close()

    def _send(self, addr, payload=(0,)):
        frame = build_frame(addr, list(payload))
        with self._lock:
            self._serial.write(frame)
            time.sleep(WRITE_DELAY)

    # -- gaits ------------------------------------------------------------
    # Each starts the board's own gait loop and returns immediately. The robot
    # keeps walking until stay_put() or reset(); there is no built-in timeout,
    # which is why the caller needs a watchdog.

    def gait(self, direction, step=STEP_MAX):
        if direction not in _GAIT_ADDR:
            raise ValueError(f'unknown gait {direction!r}, expected one of {GAITS}')
        self._send(_GAIT_ADDR[direction], [int(clamp(step, STEP_MIN, STEP_MAX))])

    def stay_put(self):
        """Set the feet down at the current phase. This is the stop."""
        self._send(ADDR_STAY_PUT)

    def reset(self):
        """Stand in the default posture, aborting any running gait or action."""
        self._send(ADDR_RESET)

    def squat(self):
        self._send(ADDR_SQUATS)

    # -- gait parameters --------------------------------------------------

    def speed(self, level):
        """Speed level 1-5, 5 fastest.

        The board wants a cycle time, not a speed, so the level is inverted
        before transmission exactly as MutoLibCore does. The vendor docstring
        claims the opposite; the code is what ships.
        """
        level = int(clamp(level, SPEED_MIN, SPEED_MAX))
        self._send(ADDR_RUN_TIME, [SPEED_MAX - level])

    def height(self, level):
        """Ride height 1 (low) to 3 (high)."""
        self._send(ADDR_HEIGHT, [int(clamp(level, HEIGHT_MIN, HEIGHT_MAX))])

    # -- camera gimbal ----------------------------------------------------

    def gimbal(self, pan=GIMBAL_HOLD, tilt=GIMBAL_HOLD):
        """Aim the camera. Pan 0-180 (0 = right), tilt 0-115 (0 = down).

        Pass GIMBAL_HOLD for an axis to leave it alone. Both axes travel in one
        two-byte frame, so a combined move costs no more than a single-axis one.

        These are servo units, not degrees -- tilt measures about 1.6 deg per
        unit. There is no feedback, so a command snaps to its target at full
        speed from wherever the servo happens to be.
        """
        if pan != GIMBAL_HOLD:
            pan = int(clamp(pan, PAN_MIN, PAN_MAX))
        if tilt != GIMBAL_HOLD:
            tilt = int(clamp(tilt, TILT_MIN, TILT_MAX))
        self._send(ADDR_PWM_SERVO, [pan & 0xFF, tilt & 0xFF])

    # -- misc -------------------------------------------------------------

    def buzzer(self, timeout):
        """0 off, 255 continuous, 1-254 sounds for timeout * 100 ms."""
        self._send(ADDR_BUZZER, [int(clamp(timeout, 0, 255))])

    def torque(self, on, servo_id=0):
        """Joint servo torque. servo_id 0 means all eighteen.

        Torque off leaves nothing holding the robot up -- support the body first.
        """
        addr = ADDR_TORQUE_ON if on else ADDR_TORQUE_OFF
        self._send(addr, [0xFE if servo_id == 0 else int(servo_id)])
